from database.config import supabase
import bcrypt

def check_teacher_exists(username: str) -> bool:
    response = supabase.table("teachers").select("username").eq("username", username).execute()
    return len(response.data) > 0

def hash_password(password: str) -> str:
    salt = bcrypt.gensalt()
    hashed_password = bcrypt.hashpw(password.encode('utf-8'), salt)
    return hashed_password.decode('utf-8')

def create_teacher(username: str, name: str, password: str):
    new_teacher = {
        "username": username,
        "name": name,
        "password": hash_password(password)
    }
    response = supabase.table("teachers").insert(new_teacher).execute()
    return response.data

def teacher_login(username: str, password: str) -> dict | None:
    response = supabase.table("teachers").select("*").eq("username", username).execute()
    if response.data:
        teacher = response.data[0]
        if bcrypt.checkpw(password.encode('utf-8'), teacher['password'].encode('utf-8')):
            return teacher
    return None

def get_all_students():
    response = supabase.table("students").select("*").execute()
    return response.data

def create_student(name, face_embedding, voice_embedding=None):
    """Insert a new student into the `students` table.

    - name: the student's full name (required).
    - face_embedding: the student's face embedding as a flat list, e.g. [128 floats].
    - voice_embedding: optional voice embedding as a flat list, e.g. [256 floats].

    `student_id` is an identity column auto-generated by the DB, so it is not set here.
    Returns the inserted row(s).
    """
    new_student = {
        "name": name,
        "face_embedding": face_embedding,
    }
    if voice_embedding is not None:
        new_student["voice_embedding"] = voice_embedding
    response = supabase.table("students").insert(new_student).execute()
    return response.data


def mark_attendance(records):
    """Insert a batch of attendance rows into the `attendance` table.

    records: a list of dicts, where each dict is a fully-formed row:
        {
            "subject_id": <int>,
            "student_id": <int>,
            "is_present": <bool>,
            "timestamp": <ISO timestamp string>,
        }

    The caller decides everything (which students, present/absent, the timestamp),
    so this helper just sends the rows as one batched insert.

    Returns the inserted rows (or an empty list when `records` is empty).
    """
    if not records:
        return []
    response = supabase.table("attendance").insert(records).execute()
    return response.data

def create_new_subject(name, subject_code, section, teacher_id):
    """Insert a new subject into the `subjects` table.

    - teacher_id: the teacher who owns this subject (foreign key).
    - subject_code: the subject's code (required, non-nullable, e.g. "CS101").
    - name: optional subject name (e.g. "Computer Science").
    - section: optional section (e.g. "A").

    `subject_id` is an identity column auto-generated by the DB, so it is not set here.
    Returns the inserted row(s).
    """
    new_subject = {
        "subject_code": subject_code,
        "name": name,
        "section": section,
        "teacher_id": teacher_id,
    }
    response = supabase.table("subjects").insert(new_subject).execute()
    return response.data

def get_teacher_subjects(teacher_id):
    """Return all subjects owned by the given teacher as a list of dicts (empty list if none)."""
    response = supabase.table("subjects").select("* , subject_student(count) , attendance(timestamp)").eq("teacher_id", teacher_id).execute()
    for subject in response.data:
        total_students = subject.get("subject_student", [{}])[0].get("count", 0) if subject.get("subject_student") else 0
        subject["total_students"] = total_students
        attendance_records = subject.get("attendance", [])
        subject["num_of_classes"] = len(set(log['timestamp'] for log in attendance_records))
        subject.pop("subject_student", None)
        subject.pop("attendance", None)
    return response.data

def student_enroll_subject(subject_id, student_id):
    """Enroll a student in a subject by inserting into the `subject_student` table.

    - subject_id: the subject to enroll in (foreign key).
    - student_id: the student enrolling (foreign key).

    Returns the inserted row(s).
    """
    new_enrollment = {
        "subject_id": subject_id,
        "student_id": student_id,
    }
    response = supabase.table("subject_student").insert(new_enrollment).execute()
    return response.data

def unenroll_student_from_subject(subject_id, student_id):
    """Unenroll a student from a subject by deleting from the `subject_student` table.

    - subject_id: the subject to unenroll from (foreign key).
    - student_id: the student unenrolling (foreign key).

    Returns the deleted row(s).
    """
    response = supabase.table("subject_student").delete().eq("subject_id", subject_id).eq("student_id", student_id).execute()
    return response.data

def get_student_subjects(student_id):
    """Return all subjects a student is enrolled in as a list of dicts (empty list if none)."""
    response = supabase.table("subject_student").select("subject_id , subjects(subject_code , name , section)").eq("student_id", student_id).execute()
    return response.data

def get_student_attendance_logs(student_id):
    """Return all attendance records for a student as a list of dicts (empty list if none)."""
    response = supabase.table("attendance").select("subject_id , is_present , timestamp , subjects(subject_code , name , section)").eq("student_id", student_id).execute()
    return response.data

def get_teacher_attendance(teacher_id):
    """Return every attendance row across all subjects this teacher owns.

    Uses an INNER join on `subjects` so only rows whose subject belongs to this
    teacher come back, and joins the student's name in too. Returns a list of
    dicts (empty if none); each row has the joined `subjects` and `students`
    dicts embedded.
    """
    response = (
        supabase.table("attendance")
        .select("* , subjects!inner(*) , students(name)")
        .eq("subjects.teacher_id", teacher_id)
        .order("timestamp", desc=True)
        .execute()
    )
    return response.data or []